Release v1.7, adds Stubby-Installer

diff --git a/amtm b/amtm
--- a/amtm
+++ b/amtm
@@ -17,8 +17,8 @@ export PATH=/sbin:/bin:/usr/sbin:/usr/bin:$PATH
 # https://opensource.org/licenses/GPL-3.0
 
 # Version, release date
-version=1.6
-release="January 21 2019"
+version=1.7
+release="January 27 2019"
 title="SNBForum Asuswrt-Merlin Terminal Menu"
 thisScript=amtm
 
@@ -85,7 +85,6 @@ install_amtm(){
 	if [ "$(nvram get jffs2_scripts)" != "1" ]; then
 		nvram set jffs2_scripts=1
 		nvram commit
-		forcereboot=1
 	fi
 
 	# install to /jffs/scripts/$thisScript
@@ -100,35 +99,24 @@ install_amtm(){
 		message="/jffs/scripts/$thisScript\\n\\n or simply with:\\n $thisScript"
 	fi
 
-	# reboot if custom scripts were not enabled before
-	if [ "$forcereboot" = "1" ]; then
-		clear
-		print_info_line
-		echo " $title"
-		echo " successfully installed!"
-		echo
-		echo " You can start it with:"
-		printf " $message\\n"
-		echo " But first, a reboot of your router is"
-		echo " required to finish the install."
-		press_enter_to "confirm"
-		[ "$0" != "/jffs/scripts/$thisScript" ] && rm -f "$0"
-		reboot
-		exit 0
+	if [ "$0" = "/jffs/scripts/$thisScript" ]; then
+		subshell=
 	else
-		if [ "$0" = "/jffs/scripts/$thisScript" ]; then
-			subshell=
-		else
-			subshell="exec"
-			rm -f "$0"
-		fi
-		"$subshell" /jffs/scripts/$thisScript " $title\\n successfully installed!\\n\\n You can start $thisScript with:\\n $message"
+		subshell="exec"
+		rm -f "$0"
 	fi
+	"$subshell" /jffs/scripts/$thisScript " $title\\n successfully installed!\\n\\n You can start $thisScript with:\\n $message"
 }
 
 remove_amtm(){
 	print_info_line
 	echo " Do you want to remove $thisScript now?"
+	echo
+	echo " Note that removing $thisScript will not remove or"
+	echo " uninstall any installed SNBForum scripts."
+	echo
+	echo " It will, however, remove the Disk check"
+	echo " script/log, along with the Format disk log."
 	continue_dialog
 	if [ -f /jffs/scripts/disk-check ]; then
 		sed -i '\~/jffs/scripts/disk-check ~d' /jffs/scripts/pre-mount
@@ -281,17 +269,17 @@ elif [ "$1" = "delete" ]; then
 	while true;do
 		printf "\\n Delete the Swap file? [1=Yes e=Exit] ";read -r continue
 		case "$continue" in
-			1)	if [ -f "$swaplocation" ]; then
-					swapoff "$swaplocation"
-					rm -rf "$swaplocation"
-					sed -i '\~swapon ~d' /jffs/scripts/post-mount
-					show_amtm " Swap file deleted:\\n $swaplocation"
-				else
-					show_amtm " No Swap file found at\\n $swaplocation"
-				fi
-				break;;
-		[Ee])	show_amtm menu;break;;
-			*)	printf "\\n input is not an option\\n";;
+			1)		if [ -f "$swaplocation" ]; then
+						swapoff "$swaplocation"
+						rm -rf "$swaplocation"
+						sed -i '\~swapon ~d' /jffs/scripts/post-mount
+						show_amtm " Swap file deleted:\\n $swaplocation"
+					else
+						show_amtm " No Swap file found at\\n $swaplocation"
+					fi
+					break;;
+			[Ee])	show_amtm menu;break;;
+			*)		printf "\\n input is not an option\\n";;
 		esac
 	done
 
@@ -362,7 +350,7 @@ else
 		if ! grep -q ". /jffs/scripts/disk-check" /jffs/scripts/pre-mount; then
 			echo ". /jffs/scripts/disk-check # Added by $thisScript" >> /jffs/scripts/pre-mount
 		fi
-		[ -f "/jffs/scripts/pre-mount" ] && chmod 0755 /jffs/scripts/pre-mount
+		chmod 0755 /jffs/scripts/pre-mount /jffs/scripts/disk-check
 
 	elif [ "$1" = "remove" ]; then
 		print_info_line
@@ -402,8 +390,7 @@ format_disk(){
 
 		pto=4;pts=4
 		case "$(uname -m)" in
-			mips)		PART_TYPES='ext2|ext3|fat|tntfs'
-						pto=3;pts=;;
+			mips)		PART_TYPES='ext2|ext3|fat|tntfs';pto=3;pts=;;
 			armv7l)		PART_TYPES='ext2|ext3|ext4|fat|tntfs';;
 			aarch64)	PART_TYPES='ext2|ext3|ext4|fat|tntfs';;
 		esac
@@ -447,17 +434,17 @@ format_disk(){
 		echo
 		echo " This will delete ALL of the following:"
 		echo
-		echo "$(/bin/mount | grep "^${devtf:0:8}" | awk -v RED=${ERR_BG} -v NC=${NC} '{print " "RED" "$1" "NC" mounted as "RED" "$3" "NC}')"
+		echo "$(/bin/mount | grep "^${devtf:0:8}" | awk -v RED="${ERR_BG}" -v NC="${NC}" '{print " "RED" "$1" "NC" mounted as "RED" "$3" "NC}')"
 		echo
 
 		printf " 1. Continue\\n 2. Return to device selection\\n"
 		while true;do
 			printf "\\n Enter selection [1-2 e=Exit] ";read -r continue
 			case "$continue" in
-				1)	break;;
-				2)	select_device;break;;
-			 [Ee])	show_amtm " Exited Format disk function";;
-				*)	printf "\\n input is not an option\\n";;
+				1)		break;;
+				2)		select_device;break;;
+				[Ee])	show_amtm " Exited Format disk function";;
+				*)		printf "\\n input is not an option\\n";;
 			esac
 		done
 	}
@@ -470,10 +457,10 @@ format_disk(){
 	while true;do
 		printf "\\n Set filesystem [2-$pto] ";read -r continue
 		case "$continue" in
-			2)	nfs=ext2;break;;
-			3)	nfs=ext3;break;;
-		[$pts])	nfs=ext4;break;;
-			*)	printf "\\n input is not an option\\n";;
+			2)		nfs=ext2;break;;
+			3)		nfs=ext3;break;;
+			[$pts])	nfs=ext4;break;;
+			*)		printf "\\n input is not an option\\n";;
 		esac
 	done
 
@@ -491,18 +478,35 @@ format_disk(){
 		done
 	fi
 
-	print_end_line
-	printf " Do you want to set a device label?\\n\\n"
-	printf " 1. No label\\n 2. Set label\\n"
-	while true;do
-		printf "\\n Enter selection [1-2] ";read -r continue
-		case "$continue" in
-			1)	label=;break;;
-			2)	printf "\\n Enter label: ";read -r label
-				break;;
-			*)	printf "\\n input is not an option\\n";;
-		esac
-	done
+	select_label(){
+		print_end_line
+		printf " Do you want to set a device label?\\n\\n"
+		printf " 1. No label\\n 2. Set label\\n"
+		while true;do
+			printf "\\n Enter selection [1-2] ";read -r continue
+			case "$continue" in
+				1)	label=;break;;
+				2)	printf "\\n Enter label: ";read -r label
+					print_end_line
+					echo " You entered this label: ${GREEN_BG} $label ${NC}"
+					echo
+					echo " Is this correct?"
+					echo
+					printf " 1. Yes, continue\\n 2. No, back to label selection\\n"
+					while true;do
+						printf "\\n Enter selection [1-2] ";read -r continue
+						case "$continue" in
+							1)	break;;
+							2)	label=;select_label;break;;
+							*)	printf "\\n input is not an option\\n";;
+						esac
+					done
+					break;;
+				*)	printf "\\n input is not an option\\n";;
+			esac
+		done
+	}
+	select_label
 
 	print_end_line
 	echo " Formatting $mtddev now!"
@@ -596,6 +600,253 @@ format_disk_log(){
 	fi
 }
 
+# 3) Install Entware
+install_Entware(){
+	NAME="$thisScript Entware installer"
+	check_entware_folder(){
+		if [ "$(/opt/bin/find /tmp/mnt/*/ -maxdepth 1 -type d -name "entware*" 2>/dev/null | wc -l)" -gt "1" ]; then
+			/opt/bin/find /tmp/mnt/*/ -maxdepth 1 -type d -name "entware*" | while read fdir; do
+				if [ "$fdir" != "$(readlink /tmp/opt)" ] && [ -f "$fdir/bin/opkg" ]; then
+					mv "$fdir" "$(dirname "$fdir")/old.$(basename "$fdir")"
+				fi
+			done
+		fi
+	}
+
+	write_jffsfile(){
+		check_nl(){ [ "$(tail -c1 "${1}"; echo x)" != "$'\nx'" ] && echo >>"${1}";}
+
+		echo " Checking /jffs/scripts entries"
+
+		if [ ! -f "/jffs/scripts/post-mount" ]; then
+			echo "#!/bin/sh" >/jffs/scripts/post-mount
+		elif [ -f "/jffs/scripts/post-mount" ] && ! head -1 /jffs/scripts/post-mount | grep -qE "^#!/bin/sh"; then
+			sed -i '1s~^~#!/bin/sh\n~' /jffs/scripts/post-mount
+		fi
+		if ! grep -q ". /jffs/scripts/post-mount.div" /jffs/scripts/post-mount; then
+			check_nl /jffs/scripts/post-mount
+			echo ". /jffs/scripts/post-mount.div # Added by $NAME" >>/jffs/scripts/post-mount
+			echo " post-mount entry added"
+		else
+			echo " OK post-mount"
+		fi
+
+		if [ ! -f "/jffs/scripts/services-stop" ]; then
+			echo "#!/bin/sh" >/jffs/scripts/services-stop
+		elif [ -f "/jffs/scripts/services-stop" ] && ! head -1 /jffs/scripts/services-stop | grep -qE "^#!/bin/sh"; then
+			sed -i '1s~^~#!/bin/sh\n~' /jffs/scripts/services-stop
+		fi
+		if ! grep -q "/opt/etc/init.d/rc.unslung stop" /jffs/scripts/services-stop; then
+			check_nl /jffs/scripts/services-stop
+			echo "/opt/etc/init.d/rc.unslung stop # Added by $NAME" >>/jffs/scripts/services-stop
+			echo " services-stop entry added"
+		else
+			echo " OK services-stop"
+		fi
+
+		if [ ! -f "/jffs/scripts/post-mount.div" ]; then
+			cat <<-EOF > /jffs/scripts/post-mount.div
+			#!/bin/sh
+
+			# Added by $NAME
+
+			OF="\$(/usr/bin/find \$1/entware*/bin/opkg 2> /dev/null)"
+
+			if [ "\$OF" ]; then
+				   ln -nsf "\$(echo "\$OF" | sed 's~/bin/opkg~~g')" /tmp/opt
+				   /opt/etc/init.d/rc.unslung start \$0
+			fi
+			EOF
+			echo " post-mount.div created"
+		else
+			echo " OK post-mount.div"
+		fi
+		chmod 0755 /jffs/scripts/post-mount /jffs/scripts/services-stop /jffs/scripts/post-mount.div
+	}
+
+	check_device(){
+		check_device_nok(){
+		rm -rf "$1/rw_test"
+		show_amtm " $1\\n has not passed the device test.\\n Check if device is read and writable."
+		}
+
+		mkdir -p $1/rw_test
+		if [ -d "$1/rw_test" ]; then
+			echo "rwTest=OK" >"$1/rw_test/rw_test.txt"
+			if [ -f "$1/rw_test/rw_test.txt" ]; then
+				. "$1/rw_test/rw_test.txt"
+				if [ "$rwTest" = "OK" ]; then
+					rm -rf "$1/rw_test"
+				else
+					check_device_nok "$1"
+				fi
+			else
+				check_device_nok "$1"
+			fi
+		else
+			check_device_nok "$1"
+		fi
+	}
+
+	case "$(uname -m)" in
+		mips)		PART_TYPES='ext2|ext3'
+					INST_URL='http://pkg.entware.net/binaries/mipsel/installer/installer.sh'
+					entVer="Entware (mipsel)";;
+		armv7l)		PART_TYPES='ext2|ext3|ext4'
+					INST_URL='http://bin.entware.net/armv7sf-k2.6/installer/generic.sh'
+					entVer="Entware (armv7)";;
+		aarch64)	PART_TYPES='ext2|ext3|ext4'
+					INST_URL='http://bin.entware.net/aarch64-k3.10/installer/generic.sh'
+					entVer="Entware (aarch64)";;
+		*)			show_amtm " $(uname -m) is an unsupported platform to install Entware on.";;
+	esac
+
+	echo " Running pre-install checks"
+
+	if [ -L "/tmp/opt" ]; then
+		# dl master check
+		if [ "$(nvram get apps_mounted_path)" ] && [ -d "$(nvram get apps_mounted_path)/$(nvram get apps_install_folder)" ]; then
+			if [ -f "/opt/etc/init.d/S50downloadmaster" ]; then
+				echo "${ERR_BG} Download Master appears to be installed ${NC}"
+				echo " $(nvram get apps_mounted_path)/$(nvram get apps_install_folder)"
+				echo " Entware and Download Master cannot be installed at the same time."
+				echo " Uninstall Download Master in 'USB Application' first."
+
+				echo
+				echo "${ERR_BG} Correct above error first before installing Entware ${NC}"
+				press_enter_to acknowledge
+				show_amtm " Correct error first before installing Entware."
+			else
+				echo "${ERR_BG} Correcting invalid Entware or Download Master settings ${NC}"
+				if [ -L "/tmp/opt" ]; then
+					rm -f /tmp/opt 2> /dev/null
+					rm -f /opt 2> /dev/null
+				fi
+				if [ -d "$(nvram get apps_mounted_path)/$(nvram get apps_install_folder)" ]; then
+					rm -rf "$(nvram get apps_mounted_path)/$(nvram get apps_install_folder)"
+				fi
+				nvram set apps_mounted_path=
+				nvram set apps_dev=
+				nvram set apps_state_autorun=
+				nvram set apps_state_enable=
+				nvram set apps_state_install=
+				nvram set apps_state_switch=
+				nvram commit
+			fi
+		else
+			if [ -L "/tmp/opt" ]; then
+				rm -f /tmp/opt 2> /dev/null
+				rm -f /opt 2> /dev/null
+			fi
+			echo "${ERR_BG} Corrected invalid Entware symlink ${NC}"
+		fi
+	fi
+
+	echo " Pre-install checks passed"
+
+	print_end_line
+	echo " Select device to install Entware to"
+	echo
+
+	i=1;noad=
+	for mounted in $(/bin/mount | grep -E "$PART_TYPES" | cut -d" " -f3); do
+		echo " $i. ${GREEN}$mounted${NC}"
+		eval mounts$i="$mounted"
+		noad="${noad}${i} "
+		i=$((i+1))
+	done
+
+	if [ "$i" = "1" ]; then
+		show_amtm " No compatible device(s) found to install\\n Entware on. A USB storage device formatted\\n with one of these file systems is required:\\n $(echo $PART_TYPES | sed -e 's/|/, /g')\\n Use Format disk (fd) to format FAT or NTFS\\n formatted devices to ext*."
+	fi
+
+	[ "$i" = "2" ] && devNo=1-1 || devNo="1-$((i-1))"
+	while true;do
+		printf "\\n Select device [$devNo e=Exit] ";read -r device
+		case "$device" in
+			[$noad])	break;;
+			[Ee])		show_amtm " Exited Entware install function";break;;
+			*)			printf "\\n input is not an option\\n";;
+		esac
+	done
+
+	echo
+	eval entDev="\$mounts$device"
+
+	echo " Running device checks on $entDev"
+
+	check_device "$entDev"
+
+	echo " Device checks passed"
+
+	if [ "$(uname -m)" = "aarch64" ]; then
+		print_end_line
+		printf " Select Entware version\\n\\n"
+		printf " This router can run 32bit or 64bit Entware.\\n"
+		printf " Unless you have a specific reason, the\\n"
+		printf " 64-bit version is recommended.\\n\\n"
+		printf " 1. 64-bit Entware\\n"
+		printf " 2. 32-bit Entware\\n"
+		while true;do
+			printf "\\n Enter your selection [1-2] ";read -r eversion
+			case "$eversion" in
+				1)	INST_URL='http://bin.entware.net/aarch64-k3.10/installer/generic.sh'
+					entVer="Entware (aarch64)";break;;
+				2)	INST_URL='http://bin.entware.net/armv7sf-k3.2/installer/generic.sh'
+					entVer="Entware (armv7)";break;;
+				*) 	printf "\\n input is not an option\\n";;
+			esac
+		done
+	fi
+
+	print_end_line
+	echo " amtm is now ready to install Entware to"
+	echo
+	echo " ${GREEN_BG} $entDev ${NC}"
+	echo
+	printf " 1. Continue\\n 2. Return to device selection\\n"
+	while true;do
+		printf "\\n Enter selection [1-2 e=Exit] ";read -r continue
+		case "$continue" in
+			1)		break;;
+			2)		echo;install_Entware;break;;
+			[Ee])	show_amtm " Exited Entware install function";;
+			*)		printf "\\n input is not an option\\n";;
+		esac
+	done
+
+	echo
+	cd /tmp
+
+	entPath="$entDev/entware"
+	[ -d "$entPath" ] && rm -rf "$entPath"
+
+	echo " Creating install directory at $entPath"
+
+	mkdir -p "$entPath"
+
+	ln -sf "$entPath" /tmp/opt
+
+	echo
+	echo " Installing $entVer, using external script"
+	echo "${GRAY}"
+	wget --timeout=10 --tries=3 --retry-connrefused -qO - "$INST_URL" | sh
+	echo "${NC}"
+
+	if [ -f "/opt/bin/opkg" ]; then
+		ENTURL="$(awk 'NR == 1 {print $3}' /opt/etc/opkg.conf)"
+		[ "$(echo $ENTURL | grep 'aarch64\|armv7\|mipsel')" ] && entVersion="Entware (${ENTURL##*/})"
+		[ -z "$entVersion" ] && entVersion=$entVer
+		check_entware_folder
+		cd
+		write_jffsfile
+		show_amtm " $entVersion install successful."
+	else
+		cd
+		show_amtm " $entVer install failed."
+	fi
+}
+
 # Use selected color theme when Diversion/AB-Solution is installed
 check_AB_theme(){
 	divconf=/opt/share/diversion/.conf/diversion.conf
@@ -644,6 +895,7 @@ show_amtm(){
 		case_1(){
 			clear
 			diversion
+			sleep 2
 			show_amtm menu
 		}
 
@@ -655,6 +907,7 @@ show_amtm(){
 			case_1(){
 				clear
 				ab-solution
+				sleep 2
 				show_amtm menu
 			}
 		else
@@ -662,6 +915,7 @@ show_amtm(){
 			case_1(){
 				clear
 				sh "$HOME/ab-solution.sh"
+				sleep 2
 				show_amtm menu
 			}
 		fi
@@ -673,6 +927,7 @@ show_amtm(){
 
 		case_1(){
 			sh "$(find /mnt/*/ab-solution.sh)"
+			sleep 2
 			show_amtm menu
 		}
 	else
@@ -682,10 +937,12 @@ show_amtm(){
 			print_info_line
 			echo " This installs Diversion,"
 			echo " the Router Adblocker."
+			echo
 			echo " Author: thelonelycoder"
 			echo " https://www.snbforums.com/threads/diversion-the-router-adblocker.48538/"
 			continue_dialog
 			curl -Os https://diversion.ch/install && sh install
+			sleep 2
 			show_amtm " Diversion installed."
 		}
 	fi
@@ -706,10 +963,17 @@ show_amtm(){
 		case_2(){
 
 			print_info_line
-			echo " This installs dnscrypt installer on your router."
+			echo " This installs dnscrypt installer on your"
+			echo " router."
+			echo
 			echo " Author: bigeyes0x0"
 			echo " https://www.snbforums.com/threads/release-dnscrypt-installer-for-asuswrt.36071/"
 			continue_dialog
+
+			if [ -f "/jffs/scripts/install_stubby.sh" ] && [ -f "/opt/etc/stubby/stubby.yml" ]; then
+				show_amtm " dnscrypt installer install failed.\\n It is not compatible with Stubby DNS\\n which is installed on this router."
+			fi
+
 			curl -L -s -k -O https://raw.githubusercontent.com/thuantran/dnscrypt-asuswrt-installer/master/installer && sh installer ; rm installer
 			show_amtm " dnscrypt installer installed."
 		}
@@ -736,17 +1000,21 @@ show_amtm(){
 			show_amtm " Entware packages updated and upgraded."
 		}
 	else
-		printf "${ERR_BG} 3 ${NC} %-9s%s\\n" "" "Menu not available"
+		printf "${ERR_BG} 3 ${NC} %-9s%s\\n" "install" "Entware"
 
 		case_3(){
 			print_info_line
-			echo " The Entware menu will be available"
-			echo " after installation by Diversion"
-			echo " or with another Entware install script."
+			echo " This installs Entware on this router."
 			echo
-			echo " The installation of Entware through"
-			echo " amtm is not currently available."
-			press_enter_to "return to menu"
+			echo " Note: If you plan to install Diversion on"
+			echo " this router, install Diversion first,"
+			echo " it includes the installation of Entware."
+			echo
+			echo " Author: thelonelycoder"
+			echo " https://www.snbforums.com/threads/diversion-the-router-adblocker.48538/"
+			continue_dialog
+			install_Entware
+			sleep 2
 			show_amtm menu
 		}
 	fi
@@ -768,6 +1036,7 @@ show_amtm(){
 			print_info_line
 			echo " This installs the latest pixelserv-tls beta version."
 			echo " Be aware this is for advanced users only."
+			echo
 			echo " Author: kvic"
 			echo " https://www.snbforums.com/threads/pixelserv-a-better-one-pixel-webserver-for-adblock.26114/"
 			print_end_line
@@ -806,6 +1075,7 @@ show_amtm(){
 
 		case_5(){
 			/jffs/scripts/firewall
+			sleep 2
 			show_amtm menu
 		}
 	else
@@ -814,6 +1084,7 @@ show_amtm(){
 		case_5(){
 			print_info_line
 			echo " This installs Skynet on your router."
+			echo
 			echo " Author: Adamm"
 			echo " https://www.snbforums.com/threads/skynet-asus-firewall-addition-dynamic-malware-country-manual-ip-blocking.16798/"
 			continue_dialog
@@ -823,7 +1094,40 @@ show_amtm(){
 			fi
 
 			curl --retry 3 "https://raw.githubusercontent.com/Adamm00/IPSet_ASUS/master/firewall.sh" -o "/jffs/scripts/firewall" && chmod +x /jffs/scripts/firewall && sh /jffs/scripts/firewall install
+			sleep 2
 			show_amtm " Skynet installed."
+		}
+	fi
+
+
+	# 6 Stubby-Installer-Asuswrt-Merlin menu
+	if [ -f "/jffs/scripts/install_stubby.sh" ] && [ -f "/opt/etc/stubby/stubby.yml" ]; then
+		printf "${GREEN_BG} 6 ${NC} %-9s%s\\n" "open" "Stubby DNS v$(grep "VERSION=" /jffs/scripts/install_stubby.sh | sed -e 's/VERSION=//;s/"//g')"
+
+		case_6(){
+			/jffs/scripts/install_stubby.sh
+			sleep 2
+			show_amtm menu
+		}
+	else
+		printf "${ERR_BG} 6 ${NC} %-9s%s\\n" "install" "Stubby DNS"
+
+		case_6(){
+			print_info_line
+			echo " This installs Stubby DNS Privacy Daemon"
+			echo " on your router."
+			echo
+			echo " Authors: Xentrk, Adamm"
+			echo " https://www.snbforums.com/threads/stubby-installer-asuswrt-merlin.49469/"
+			continue_dialog
+
+			if [ -d "/jffs/dnscrypt" ] || [ -f "/opt/sbin/dnscrypt-proxy" ]; then
+				show_amtm " Stubby DNS install failed. It is not\\n compatible with dnscrypt installer which\\n is installed on this router."
+			fi
+
+			/usr/sbin/curl --retry 3 "https://raw.githubusercontent.com/Xentrk/Stubby-Installer-Asuswrt-Merlin/master/install_stubby.sh" -o "/jffs/scripts/install_stubby.sh" && chmod 755 /jffs/scripts/install_stubby.sh && sh /jffs/scripts/install_stubby.sh
+			sleep 2
+			show_amtm " Stubby DNS installed."
 		}
 	fi
 
@@ -951,6 +1255,7 @@ show_amtm(){
 			3)			case_3;break;;
 			4)			case_4;break;;
 			5)			case_5;break;;
+			6)			case_6;break;;
 
 			# System tools
 			swap|swp|sw)case_swp;break;;
